---
functional:
  - Создать форму регистрации для пользователей
  - Форма регистрации должна содержать поле Nickname, Email, Password, Password Confirmation, кнопку Submit, кнопки Sign in with Github, Sign with Discord 
  - Имя пользователей должно содержать от 3 до 16 символов
  - Пароль должен содержать от 6 до 16 символов
  - Подтверждение пароля должно совпадать с паролем
  - После успешной регистрации открывается главная страница приложения
  - После неправильно введенных значений в форме регистрации можно повторить попытку входа без перезагрузки страницы
  - Создать форму входа для пользователей, в котором должно быть поле Email, Password, кнопка Submit, Sign in with Github, Sign with Discord, Sign Up
  - Форма входа пишет ошибку, если введено неправильная почта или пароль
  - После неправильно введенных значений в форме входа можно повторить попытку входа без перезагрузки страницы
  - После успешного входа открывается главная страница приложения
  - Приложение должно запоминать, что пользователь авторизован. При перезагрузке страницы пользователь должен оставаться авторизованным
  - На главной странице есть таблица лидеров за неделю, за месяц, за весь период LIMIT 7строк
  - На главной странице есть таблица LOBBY, TOURNAMENTS, HISTORY
  - При нажатии на LOBBY появляется таблица с 5 строками, столбцы Level, State, Players, Actions
  - При нажатии на TOURNAMENTS появляется 2 таблицы. Live tournaments и Completed tournaments
  - В таблице Live tournaments есть столбцы Title, Starts_at, Actions
  - В таблице Completed tournaments есть столбцы Title, Type, Starts_at, Actions
  - При нажатии на HISTORY появляется таблица столбцы Level, Players, Date, Actions
  - Внизу главной страницы есть окно чата. Видны онлайн пользователи и их количество. Можно написать в группу. Можно отправить личное сообщение.
  - На гланой странице есть кнопка CREATE A GAME
  - При нажатии в шапке на Codebattle переход на главную страницу
  - В шапке видно количество онлайн пользователей и данные пользователя
  - При нажатии на пользователя в шапке появляется выпадающее меню. Там информация о пользователе, настройки, рейтинг, задачи, турниры. Ссылки на код проекта, на страницу хекслета, группу в дискорде и телеграмме. 
  - В выпадающем меню кнопка Sign Out, чтобы выйти из аккаунта
  - При создании игры возможность выбрать уровень сложности. Элементарный, простой, средний, сложный уровни
  - При создании игры возможность выбрать тип игры. С другим пользователем, другом, или ботом
  - При создании игры возможность выбрать продолжительность игры
  - При создании игры возможность выбрать игру по названию или тегу
  - На странице игры видеть время до окнчания, поле с заданием, поле с выводом
  - На странице игры возможность менять язык интерфейса с английского на русский и наоборот
  - На странице игры возможность выбрать язык программирования, кнопки для проверки кода, сброса и для того, чтобы сдаться
  - Возможность поменять тему с темного на светлый и наоборот редактора кода
  - На странице игры возможность включить редактор кода Vim
  - На странице игры должна быть подсказка/гид для обучения пользователя
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Менять язык в приложении
  - Изменять профиль, менять Nickname, пароль, аватар
  - Удалять аккаунт
