---
functional:
  - Создать форму регистрации для пользователей
  - Форма регистрации должна содержать поле Nickname, Email, Password, Password Confirmation, кнопку Submit, кнопки Sign in with Github, Sign with Discord 
  - Имя пользователей должно содержать от 3 до 16 символов
  - Пароль должен содержать от 6 до 16 символов
  - Подтверждение пароля должно совпадать с паролем
  - После успешной регистрации открывается главная страница приложения
  - После неправильно введенных значений в форме регистрации можно повторить попытку входа без перезагрузки страницы
  - Создать форму входа для пользователей, в котором должно быть поле Email, Password, кнопка Submit, Sign in with Github, Sign with Discord, Sign Up
  - Форма входа пишет ошибку, если введено неправильная почта или пароль
  - После неправильно введенных значений в форме входа можно повторить попытку входа без перезагрузки страницы
  - После успешного входа открывается главная страница приложения
  - Приложение должно запоминать, что пользователь авторизован. При перезагрузке страницы пользователь должен оставаться авторизованным
  - На главной странице есть таблица лидеров за неделю, за месяц, за весь период
  - На главной странице есть окно LOBBY, TOURNAMENTS, HISTORY
  - На гланой странице есть кнопка CREATE A GAME
  - 
  

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - В корзине должна быть возможность указывать/выбирать количество товара
